### ISSUE TITLE
Authentication with SSH Keys Doesn't Work

### ISSUE THREAD

**Issue by MattHodge** [DarwinJS/ChocoPackages#11]
When installing the chocolatey package (`win32-openssh 2016.05.30.20160827`), you cannot authenticate with just an SSL Key using `Enter-PSSession -HostName myhostname -UserName myusername -KeyPath ~/.ssh/myprivkey`

Running the following and restarting the machine fixes the issue: 
```powershell
  $subkey = 'SYSTEM\CurrentControlSet\Control\Lsa'
  $value  = 'Authentication Packages'
  $reg = [Microsoft.Win32.RegistryKey]::OpenBaseKey('LocalMachine', 0)
  $key = $reg.OpenSubKey($subkey, $true)
  $arr = $key.GetValue($value)
  if ($arr -notcontains 'ssh-lsa') {
    $arr += 'ssh-lsa'
    $key.SetValue($value, [string[]]$arr, 'MultiString')
  }
```

**Comment by DarwinJS** [comment]
@MattHodge - could you please detail the exact package command line you used to install the package?  Thanks!

**Comment by MattHodge** [comment]
I used :

choco install -y win32-openssh -version 2016.05.30.20160827 --params='/SSHServerFeature /KeyBasedAuthenticationFeature /UseNTRights'

Windows 2012 R2 with WMF5

**Comment by DarwinJS** [comment]
Thanks @MattHodge for your patience and time in finding and reporting the bug - I will be looking into this!

**Comment by DarwinJS** [comment]
@MattHodge - this should also be fixed - looks like the install instructions changed for the string to be added and I didn't pick that up in a previous release.
