### ISSUE TITLE
Feature request: add to path immediately, and check for other ssh.exe

### ISSUE THREAD

**Issue by kobeyu** [DarwinJS/ChocoPackages#12]
After the things that happened to me here: https://github.com/PowerShell/Win32-OpenSSH/issues/354

Could the install script update the current running process' Path?

Also it might be worth seeing if there is any other ssh.exe on the path and warning the user?

**Comment by DarwinJS** [comment]
@kobeyu - the script does set the path.  Here for a pure chocolatey install: https://github.com/DarwinJS/ChocoPackages/blob/master/openssh/tools/chocolateyinstall.ps1#L255

and here for the barebonesinstaller: https://github.com/DarwinJS/ChocoPackages/blob/master/openssh/tools/chocolateyinstall.ps1#L282

Is there anything on your system that might have prevented that from happening or being recognized?  Maybe you could gist your chocolatey log of the install?

**Comment by DarwinJS** [comment]
@kobeyu - the main reason it cannot be added to the path immediately is because the chocolateyinstall.ps1 runs as a grandchild process to your current process - so it cannot set the path in a process that is several levels higher in the call stack.

I am thinking we could do your second request by using get-command ssh.exe at the end and warning if it does not point to the one we just installed.

**Comment by kobeyu** [comment]
Yeah, I think what I want here is not practical (Though there is the chocolatey powershell command `RefreshEnv.cmd`, which might improve things). Most of my confusion was caused by scp.exe not correctly locating ssh.exe as documented in the referenced bug: https://github.com/PowerShell/Win32-OpenSSH/issues/354

I'm happy for you to close this however you like (but I won't do so now in case you want to do anything about this).

**Comment by DarwinJS** [comment]
Sure if you run Refreshenv.cmd in the shell you called the package from then you will get the benefit.

Oh wait - the oneliner script I created for this could do that if enhanced - I can take this as a PR against: https://github.com/DarwinJS/ChocoPackages/blob/master/openssh/InstallChoco_and_win32-openssh.ps1

In that case you are running my code in your exact shell session so I could refresh then environment for you so it is immediately available.

It also installs chocolatey inline if it is not present.

**Comment by DarwinJS** [comment]
This enhancement is added in the 0.0.2.0 chocolatey package when you use the single shot install scripts noted below.

Release Notes (from https://chocolatey.org/packages/openssh/0.0.2.0):
- NEW: /SSHAgentFeature - enables SSH agent for use with client tools when /SSHServerFeature is not used.
- NEW: Sample Dockerfile included for Server Core 2016 or Nano.
- FIX: Uninstall improved.
- NEW: InstallChoco_and_win32-openssh.ps1 and InstallChoco_and_win32-openssh_with_server.ps1 both refresh the environment after installing OpenSSH so it can be used in the same console it was installed in.
- FIX: ssh-add is only run after ssh-agent is started.
- FIX: sshd and ssh-agent are always started (if installed), however, a warning to reboot is still generated if key based authentication is being used.

Please reopen if you find problems.
