### ISSUE TITLE
Update visualstudio2015testagents to update 3

### ISSUE THREAD

**Issue by JorritSalverda** [DarwinJS/ChocoPackages#19]
This package is still an old test agent that doesn't support parallel execution of tests.

Can it be updated to update 3? Download link is https://go.microsoft.com/fwlink/?LinkId=615472&clcid=0x409)

Thx

**Comment by JorritSalverda** [comment]
Created https://github.com/DarwinJS/ChocoPackages/pull/20 for this.

**Comment by DarwinJS** [comment]
Thanks!
I will update it.
D.
