### ISSUE TITLE
OpenSSH: Offline install (without chocolatey) doesn't work on Windows Server 2008

### ISSUE THREAD

**Issue by geld0r** [DarwinJS/ChocoPackages#24]
First off, thank you for this! Installing on Windows Server 2012 worked like a charm and probably saved me hours of fiddling around.

However, I also would like to install on an older Windows Server 2008.
The offline installation without chocolatey (as described [here](https://github.com/DarwinJS/ChocoPackages/blob/master/openssh/readme.md#complete-offline-install-wout-chocolatey-nor-wow64-nor-powershell-5)) for the Server doesn't work there and fails when trying to extract OpenSSH to the temp folder:
```

Copy-Item : Cannot find path 'C:\Users\ADMINI~1\AppData\Local\Temp\2\OpenSSHTemp' because it does not exist.
At C:\fluidops\Tools\OpenSSH\tools\chocolateyinstall.ps1:299 char:10
+ Copy-Item <<<<  "$ExtractFolder\*" "$PF" -Force -Recurse
    + CategoryInfo          : ObjectNotFound: (C:\Users\ADMINI...p\2\OpenSSHTemp:String) [Copy-Item], ItemNotFoundExce
   ption
    + FullyQualifiedErrorId : PathNotFound,Microsoft.PowerShell.Commands.CopyItemCommand
```

With my limited PS knowledge, I was able to set the path to the tempfolder manually in `chocolateyinstall.ps1`

After that it fails when trying to start the SSH agent:
```
Start-Service : Service 'ssh-agent (ssh-agent)' cannot be started due to the following error: Cannot start service ssh-
agent on computer '.'.
At C:\Tools\OpenSSH\tools\chocolateyinstall.ps1:315 char:16
+   Start-Service <<<<  ssh-agent
    + CategoryInfo          : OpenError: (System.ServiceProcess.ServiceController:ServiceController) [Start-Service],
   ServiceCommandException
    + FullyQualifiedErrorId : CouldNotStartService,Microsoft.PowerShell.Commands.StartServiceCommand
```

Does a workaround exist for that, e.g. updating Powershell or installing using chocolatey after all?

**Comment by geld0r** [comment]
Ok, this was a false alarm and caused by an outdated PowerShell version being used. On Windows Server 2008 that seems to be 2.x by default which doesn't work with the installation script. I updated to Version 5 and that worked like a charm, Thanks!

**Comment by DarwinJS** [comment]
@geld0r - thanks for reporting this.  From your problem description, this seemed very odd - you should not have to upgrade PowerShell to get it working.

I was able to reproduce it on Server 2008 R2 and it appears to be a challenge with how PowerShell 2 was interpreting the call to 7zip.

I changed the implementation to use "Start-Process" and got it working on a vanilla Server 2008 R2 / Powershell 2 machine.

So if you have any more of these to install, you should no longer need to upgrade PowerShell to run the standalone installer. (barebones.ps1)

Version 0.0.9.20170226 contains the fix.

**Comment by geld0r** [comment]
Thanks for looking itno this. I am done with the machines I set out to install this on.
Given the fact that this was a smooth ride, I'll be sure to use it again for the next windows machine that I intend to install OpenSSH on though!

**Comment by geld0r** [comment]
Actually I got to try this out already. One stubborn server didn't want to upgrade. The new package worked perfectly. Thanks again!
