### ISSUE TITLE
[openssh] Error « The "=" operator is missing after a named argument »

### ISSUE THREAD

**Issue by C-Duv** [DarwinJS/ChocoPackages#26]
Running `choco install openssh -params '"/SSHServerFeature"'`, I get a *ERROR: The "=" operator is missing after a named argument.* error

Here is detailled error log:

    NO ACTIONS REQUIRED! Account already in "Logon as a Service"
    Done.
    WARNING: You have specified SSHServerFeature - this machine is being configuredas an SSH Server including opening port 22.
    WARNING: You have specified SSHServerFeature - a new lsa provider will be installed.
    ERROR: The "=" operator is missing after a named argument.
    The install of openssh was NOT successful.
    Error while running 'C:\ProgramData\chocolatey\lib\openssh\tools\chocolateyinstall.ps1'.
     See log for details.
    
    Chocolatey installed 0/1 packages. 1 packages failed.
     See the log for details (C:\ProgramData\chocolatey\logs\chocolatey.log).
    
    Failures
     - openssh (exited -1) - Error while running 'C:\ProgramData\chocolatey\lib\openssh\tools\chocolateyinstall.ps1'.
     See log for details.

Files are created in `C:\Program Files\OpenSSH-Win64` and service `sshd-agent` is created, but not `sshd`.

Versions:
* Windows 7 Pro 64-bits
* Chocolatey 0.10.3
* PowerShell 2.0

**Comment by DarwinJS** [comment]
Thanks for the report!  I was able to reproduce this and fix it.

It only affected using /SSHServerFeature under PSH 2 - which is a little fussier about how to declare the function parameters in the supporting code in fileinuseutils.ps1

The fix is in Version 0.0.9.20170313, which is in automated moderation as of this writing.

**Comment by C-Duv** [comment]
Thanks :)
