### ISSUE TITLE
Additional steps to take by installer?

### ISSUE THREAD

**Issue by ebekker** [DarwinJS/ChocoPackages#31]
Thanks for the great project!

After trying this out, there were a couple additional manual steps that I had to take to get the SSH service operable and accessible based on the (installation instructions](https://github.com/PowerShell/Win32-OpenSSH/wiki/Install-Win32-OpenSSH):
* Generate all the host keys:  `ssh-keygen.exe -A`
* Open up the host's firewall:  `New-NetFirewallRule -Protocol TCP -LocalPort 22 -Direction Inbound -Action Allow -DisplayName SSH`

Is there a reason why the installer doesn't complete these steps for a user (technical or philosophical)?

**Comment by DarwinJS** [comment]
@ebekker - both of those steps should be taken by the installer when you use the switch -params '"/SSHServerFeature"'

Can you please post the command line you used?

Can you please grab your logs from $env:chocolateyinstall\logs and post them to gist.github.com and link them here.

**Comment by ebekker** [comment]
You are correct -- my mistake, I installed your package on two systems, a server and a workstation and I confused the configuration between the two of them.  Everything (as far as installation) seems to be setup correctly.

Thanks for the great installer!  On suggestion -- I would put the flag for enabling/distinguishing for server (sshd) installation near the top of the docs or a mention and reference to the flag near the top that links to the details within.
