### ISSUE TITLE
Request to update openssh to v0.0.15.0

### ISSUE THREAD

**Issue by gbraad** [DarwinJS/ChocoPackages#34]
This way we have support for docker-machine, minikube (https://github.com/kubernetes/minikube/issues/1537) and minishift (https://github.com/minishift/minishift/issues/957). This was reported to win32-openssh as https://github.com/PowerShell/Win32-OpenSSH/issues/738

The needed fix is: https://github.com/PowerShell/Win32-OpenSSH/issues/666

**Comment by DarwinJS** [comment]
@gbraad - sorry for the delay.  My testing of the Chocolatey package revealed multiple problems with the new PowerShell helpers included in the OpenSSH 0.0.15.0 package and I have been working with the openssh team to resolve them before putting out a package that does not work on all target platforms.

We are getting close - thanks for your patience!

**Comment by gbraad** [comment]
Thanks. did you report these as issues, so I can track them or help?

**Comment by DarwinJS** [comment]
@gbraad - yes you can see the exchanges in the win32-openssh issues.  However, all problems seem to be solved - I will include the latest fixed opensshutils.psm1 in the chocolatey package as soon as @bingbing8 is able to do a PR with the updated files.

There is a working copy of the package you can test (with the version of the module that I fixed) - those instructions are here: https://github.com/PowerShell/Win32-OpenSSH/issues/763

In fact, it's a great time to get your feedback as I could possibly get fixes into this release for you if you find problems.

**Comment by DarwinJS** [comment]
@gbraad - FYI - I just retested on Nano after all the fixes to the module and it appears to work fine.

**Comment by DarwinJS** [comment]
@gbraad - just discovered another problem - should only effect you if you are upgrading openssh and have a bunch of authorized_keys files in user folders.

See new update to: https://github.com/PowerShell/Win32-OpenSSH/issues/758

**Comment by DarwinJS** [comment]
This is finally published - a lot of changes had to be made to the new opensshutils.psm1 provided by Microsoft and then I pulled the newest version into the 0.0.15.0 package.

**Comment by gbraad** [comment]
Thank you. Sorry for the belated response, but have been on sick-leave. Will test this and if I see regression I will file them.
