### ISSUE TITLE
Installation error: "The variable '$RunningOnNano' cannot be retrieved…"

### ISSUE THREAD

**Issue by alexchandel** [DarwinJS/ChocoPackages#35]
Installing this package on Window 2008 R2 datacenter for the first time, with no previous chocolatey or openssh installation, yields the following error: "The variable '$RunningOnNano' cannot be retrieved because it has not been set."
<img width="602" alt="screen shot 2017-06-13 at 5 18 17 pm" src="https://user-images.githubusercontent.com/637714/27107609-f5a21abc-5066-11e7-9d3d-7f8340a157c4.png">

The installation then appears to fail, and chocolatey doesn't consider the package installed.

**Comment by DarwinJS** [comment]
@alexchandel - version 0.0.15.20170613 has fix for this - let me know if this fixes the problem by closing this issue or adding to it if it does not.
