### ISSUE TITLE
Add parameter to allow user to set $TargetLocation to install

### ISSUE THREAD

**Issue by tapuzzo-fsi** [DarwinJS/ChocoPackages#48]
Some buggy tools choke when path contains spaces.  Should be possible to specify `/InstallLocation=c:\tools\openssh` or similar when installing.

**Comment by DarwinJS** [comment]
The challenge is that locations outside of Program Files and system32 are susceptible to being hijacked by malware with regular user permissions.  I will keep this on the request list.  Would probably also require a /AllowInsecureInstallLocation to move it to outside of Program Files and/or system32.
