### ISSUE TITLE
Unable to open port 22

### ISSUE THREAD

**Issue by saurabhverma999** [DarwinJS/ChocoPackages#51]
![unbenannt](https://user-images.githubusercontent.com/32668117/33070122-3337017a-ceb7-11e7-8822-3adaadd65cc9.PNG)

is there an issue with my firewall or is there something else??

Thanks in advance!!

**Comment by DarwinJS** [comment]
That error means another sshd server is already using port 22.

This command should show what is listening on port 22:
`netstat -a -b | sls ":22" -Context 3`

Also, this command can show if any other services have ssh in them:
`get-service *ssh*`

On Windows 10, the most common reason for this is having installed "Windows Services for Linux"

You can either disable the existing services on port 22 or run sshd on another port like this:
`choco install -y openssh -params '"/SSHServerFeature /SSHServerPort:3834"'`

**Comment by saurabhverma999** [comment]
I used netstat -anop TCP  this to check the occupied ports list.

It does not show anything hearing on port 22.

The other commands did not work with me.

Is it that i have to check my firewall settings or shall i update my powershell ??

Thanks!

**Comment by DarwinJS** [comment]
Looking closer it appears you still have the files from an attempt at a manual install

You should remove all files from "c:\program files\openssh" - but first run `stop-servixe *say*`

**Comment by saurabhverma999** [comment]
I deleted the previous version and downloaded the new version of OpenSSH and then tried following the universal installer , still i am getting the same error.

**Comment by saurabhverma999** [comment]
It seems 2 services named ssh-agent and sshd have ssh running in them. but satus of both the processes is stopped so i dont think these will block port 22.

**Comment by saurabhverma999** [comment]
when i give **ssh 127.0.0.1** command from my server pc on which i am running OpenSSH, it says 

**port 22 : Connection refused**

**Comment by saurabhverma999** [comment]
Now i am able to access port 22.

Since there were **sshd and ssh-agent** somehow occupying the port i uninstalled the complete OpenSSH using **powershell.exe -ExecutionPolicy Bypass -File uninstall-sshd.ps1**

And then **sshd** and **ssh-agent** were removed from the process list automatically.
