### ISSUE TITLE
Chocolatey uninstall fails due to missing repair-filepermission

### ISSUE THREAD

**Issue by coldacid** [DarwinJS/ChocoPackages#52]
```
Running on: Windows 10 Pro Insider Preview, (Professional)
WARNING: Removing all config and server keys as requested by /DeleteConfigAndServerKeys
ERROR: The term 'repair-filepermission' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of the name, or if a path was included, verify that the path is correct and try again.
openssh uninstall not successful.
Error while running 'C:\ProgramData\chocolatey\lib\openssh\tools\chocolateyuninstall.ps1'.
 See log for details.
openssh not uninstalled. An error occurred during uninstall:
 openssh uninstall not successful.

Chocolatey uninstalled 0/1 packages. 1 packages failed.
 See the log for details (C:\ProgramData\chocolatey\logs\chocolatey.log).

Failures
 - openssh (exited -1) - Error while running 'C:\ProgramData\chocolatey\lib\openssh\tools\chocolateyuninstall.ps1'.
 See log for details.
```

**Comment by DarwinJS** [comment]
@coldacid - thanks for reporting.  It looks like the code in OpenSSHUtils.psm1 was updated and no longer provides this function.  I have reported that here: https://github.com/PowerShell/Win32-OpenSSH/issues/968 and I will look to update the next package version to make the equivalent calls.

**Comment by coldacid** [comment]
No prob, thanks!

**Comment by saurabhverma999** [comment]
# following!

**Comment by saurabhverma999** [comment]
In the mean time, could you suggest any other way in which i can cleanly and completely uninstall OpenSSH?? Thanks!

**Comment by DarwinJS** [comment]
OK I found out this is actually my code and it will be fixed in the next revision.  I have updated PowerShell/Win32-OpenSSH#968  with details.

@saurabhverma999 - when you ask about a work around for a completely clean install, are you talking about a few test systems or a huge fleet of systems?

**Comment by DarwinJS** [comment]
@saurabhverma999 - I have commited the fixed file and you can drop it into the right place in an existing install and accomplish an uninstall with the chocolatey commands.

Take this file: https://github.com/DarwinJS/ChocoPackages/blob/master/openssh/tools/chocolateyuninstall.ps1

and on a system where openssh:
1. Is **already installed**
2. **by Chocolatey**

Overwrite:
"$env:ChocolateyInstall\lib\openssh\tools\ChocolateyUninstall.ps1"

**Comment by saurabhverma999** [comment]
@DarwinJS , I wish to do complete uninstall once. I tried uninstalling but wasnt successful. Now whenever i give commands such as net start sshd or net stop sshd, it says command is invalid.

But whenever i type ssh , i get the list of available commands. I am so able to log into the server using ssh command. 

When I open all the running processes in the background, i cant find sshd and ssh agent running.

Hence, i wish to uninstall it completely once

**Comment by saurabhverma999** [comment]
@DarwinJS  , It worked. Thank You!!

**Comment by king6cong** [comment]
These lines will help for newcomers in powershell (take from @DarwinJS ):

```
$url="https://raw.githubusercontent.com/DarwinJS/ChocoPackages/master/openssh/tools/chocolateyuninstall.ps1"
Invoke-WebRequest -Uri $url -OutFile $env:ChocolateyInstall\lib\openssh\tools\ChocolateyUninstall.ps1
cuninst -y openssh -params '"/SSHServerFeature /DeleteConfigAndServerKeys"'
```

**Comment by DarwinJS** [comment]
@king6cong - that's a great automated way to patch uninstall for any Chocolatey package - thanks for sharing!
