### ISSUE TITLE
ssh_config file missing

### ISSUE THREAD

**Issue by DaburLal** [DarwinJS/ChocoPackages#54]
After using universal installer, ssh_config file is missing from the installation package.

I can only find sshd_config.

Kindly guide me.

Thanks!

**Comment by DarwinJS** [comment]
There has never been an ssh_config file in the Microsoft provided zips - you must create it if you want one.  In the most recent versions I believe you would create it in c:\programdata\ssh.

However, I have created an issue asking for clarification: https://github.com/PowerShell/Win32-OpenSSH/issues/1186
