### ISSUE TITLE
Installation issue for openssh with /PathSpecsToProbeForShellEXEString parameter

### ISSUE THREAD

**Issue by stevehipwell** [DarwinJS/ChocoPackages#58]
When installing openssh and specifying the */PathSpecsToProbeForShellEXEString* parameter the following error is returned.

**ERROR: The running command stopped because the preference variable "ErrorActionPreference" or common parameter is set to Stop: Cannot find path 'HKEY_LOCAL_MACHINE\SOFTWARE\OpenSSH' because it does not exist.**

This is a new issue in either 1.0.0.0 or 1.0.0.20180131.

**Comment by stevehipwell** [comment]
On further investigation it appears that the issue is in the `Set-SSHDefaultShell` command as the same error is returned if SSH is installed and then this command is used.

**Comment by bagajjal** [comment]
Yeah it's a bug as the registry creation logic is in ssh-agent. Ssh-agent is an optional component to run... As a workaround just start and stop the ssh-agent service..

**Comment by DarwinJS** [comment]
I will also update that script with an idempotent creation of the registry key so the bases are covered in 1.0.0.0

**Comment by DarwinJS** [comment]
Should be fixed in 1.0.0.20180201 which was just pushed.

**Comment by stevehipwell** [comment]
@DarwinJS - I'm now seeing a different error.
```
ERROR: At C:\Program Files\OpenSSH-Win64\Set-SSHDefaultShell.ps1:200 char:145
+ ... rShellEXEString"
+                    ~
The string is missing the terminator: ".

At C:\Program Files\OpenSSH-Win64\Set-SSHDefaultShell.ps1:183 char:7
+       {
+       ~
Missing closing '}' in statement block.

At C:\Program Files\OpenSSH-Win64\Set-SSHDefaultShell.ps1:179 char:5
+     {
+     ~
Missing closing '}' in statement block.

At C:\Program Files\OpenSSH-Win64\Set-SSHDefaultShell.ps1:175 char:3
+   {
+   ~
Missing closing '}' in statement block.

At C:\Program Files\OpenSSH-Win64\Set-SSHDefaultShell.ps1:154 char:1
+ {
+ ~
Missing closing '}' in statement block.

At C:\Program Files\OpenSSH-Win64\Set-SSHDefaultShell.ps1:124 char:1
+ {
+ ~
Missing closing '}' in statement block.
```

**Comment by DarwinJS** [comment]
Weird - there were some corrupt characters in the code I added.  Retyped the same code and it's good now.

Version 1.0.0.20180202 was just pushed.

**Comment by stevehipwell** [comment]
@DarwinJS - That appears to have fixed it, thanks!
