### ISSUE TITLE
Uninstall commands are incorrect

### ISSUE THREAD

**Issue by Suncatcher** [DarwinJS/ChocoPackages#60]
Uninstall instruction list such command for removing leftovers:

    rd -recurse "$env:ProgramFiles\nuget\packages\openssh"

However, now the package fetched is openssh.7.6.0.1 and directory name is also wrong.

The command should be following

    rd -recurse "$env:ProgramFiles\PackageManagement\NuGet\Packages\openssh.7.6.0.1"

**Comment by DarwinJS** [comment]
Thanks for your bug report.

The NuGet cached folder can be one of two locations depending on which OS you deploy to.  This is visible in a prevoius step.

The correction has been made to `rd -recurse "$NuGetPkgRoot\openssh"` which will catch both possible cases for the NuGet cache folder.
