### ISSUE TITLE
WARNING: The command line arguments passed to the MSI are incorrect. If you passed in additional arguments, please adjust. Otherwise followup with the package maintainer(s) to get this fixed. This is most likely an issue with the 'virtualmachineconverter' package and not with Chocolatey itself. Please follow up with the package maintainer(s) directly.

### ISSUE THREAD

**Issue by sboulianne** [DarwinJS/ChocoPackages#65]
from 'https://download.microsoft.com/download/9/1/E/91E9F42C-3F1F-4AD9-92B7-8DD65DA3B0C2/mvmc_setup.msi'
Progress: 100% - Completed download of C:\Users\Sebastien Boulianne\AppData\Local\Temp\chocolatey\virtualmachineconverter\3.1\mvmc_setup.msi (23.81 MB).
Download of mvmc_setup.msi (23.81 MB) completed.
Hashes match.
Installing virtualmachineconverter...
WARNING: The command line arguments passed to the MSI are incorrect. If you passed in additional arguments, please adjust. Otherwise followup with the package maintainer(s) to get this fixed. This is most likely an issue with the 'virtualmachineconverter' package and not with Chocolatey itself. Please follow up with the package maintainer(s) directly.
ERROR: Running ["C:\WINDOWS\System32\msiexec.exe" /i "C:\Users\Sebastien Boulianne\AppData\Local\Temp\chocolatey\virtualmachineconverter\3.1\mvmc_setup.msi" /qn /l*v C:\Users\Sebastien Boulianne\AppData\Local\Temp\chocolatey\virtualmachineconverter.log ] was not successful. Exit code was '1639'. Exit code indicates the following: The command line arguments passed to the MSI are incorrect. If you passed in additional arguments, please adjust. Otherwise followup with the package maintainer(s) to get this fixed. This is most likely an issue with the 'virtualmachineconverter' package and not with Chocolatey itself. Please follow up with the package maintainer(s) directly..
The install of virtualmachineconverter was NOT successful.
Error while running 'C:\ProgramData\chocolatey\lib\virtualmachineconverter\tools\chocolateyInstall.ps1'.
 See log for details.

Chocolatey installed 0/1 packages. 1 packages failed.
 See the log for details (C:\ProgramData\chocolatey\logs\chocolatey.log).

Failures
 - virtualmachineconverter (exited 1639) - Error while running 'C:\ProgramData\chocolatey\lib\virtualmachineconverter\tools\chocolateyInstall.ps1'.
 See log for details.

Please fix it asap.

**Comment by DarwinJS** [comment]
I believe this error is due to the fact that you have a space in your user id which then puts a space in the full path to the temp folder.  I have updated the package to try to account for this - please try version 3.1.0.20180613 when it becomes available (in automated moderation now).

**Comment by DarwinJS** [comment]
Please close this issue if this fixes the problem.

**Comment by sboulianne** [comment]
Thanks for the fix!
