### ISSUE TITLE
Update Choco install for win32-openssh to handle client only and ssh-agent 

### ISSUE THREAD

**Issue by dragon788** [DarwinJS/ChocoPackages#7]
I believe we had discussed this elsewhere, but I can't find where that was. I want to use win32-openssh to perform as an ssh client for vagrant (which it does mostly work for) but also for other hosts, and if I don't perform a manual install with all the options I don't have an ssh-agent that I can use easily.

**Comment by DarwinJS** [comment]
Could you please detail the steps you use to get the agent working with the client as you describe?  Is it just configuring and starting the ssh-agent service?

**Comment by dragon788** [comment]
This has been a challenge because starting the SSH agent requires
administrator permissions and so unless starting an elevated session it
will abort. I'm thinking to make this work properly it will probably be
necessary to run the SSH agent on a per user basis in an elevated session
at startup and export (setx and set) an SSH_environment variable that has a
path to the SSH agent session file similar to how it's typically done on
Linux. This allows it to be shared between terminal/consoles from the same
user without leaking it to other users that don't have administrator
permission. It may be possible to set up a scheduled task or a service that
triggers on user login comma but I haven't explored those options because
it hasn't been and extremely pressing need yet.

Posh git and ConEmu both assume that the SSH agent binary in the path is
the cygwin version so they attempt to start it in the manner that is
compatible with that. So far this has not worked well with the Windows open
SSH version. So far I have had little luck in using the windows console
with windows open SSH for git, butt since get for Windows adds itself to
the path if it is earlier in the path then openssh then typically get
operation still work although they require interactive prompting. In many
cases this means opening git Bash and using its SSH agent instead.

Right now the only thing I've been using the Windows open SSH for is being
able to call vagrant SSH into a virtual machine which doesn't require the
SSH agent because under the covers that call assumes a few paths and uses a
key with no passphrase.

**Comment by DarwinJS** [comment]
Including @SteveL-MSFT

hmmm - we could create a .manifest file that forces windows to prompt for admin only when ssh-agent is launched.  Or the development team could embed a manifest if it isn't viewed as "too legacy windows-ish".  This shouldn't affect it's operation as a service since it would be launched in admin context in that case.

This would ensure that no matter the elevation status of the launching process, windows would know to present a UAC prompt.

I guess a deeper question is why should the agent require admin - shouldn't a non-admin user be able to use ssh-agent for, say github access.

If it ends up that handling this is best done within the EXE (internal manifesting) then this request would need to be put against the actual product - not the packaging.

**Comment by DarwinJS** [comment]
Ok - on the next cycle of the package I will add an option for the ssh agent only without the server.  If you pick server, agent will be automatically installed as well.

**Comment by DarwinJS** [comment]
This enhancement is addedd in the 0.0.2.0 chocolatey package.

Release Notes (from https://chocolatey.org/packages/openssh/0.0.2.0):
- NEW: /SSHAgentFeature - enables SSH agent for use with client tools when /SSHServerFeature is not used.
- NEW: Sample Dockerfile included for Server Core 2016 or Nano.
- FIX: Uninstall improved.
- NEW: InstallChoco_and_win32-openssh.ps1 and InstallChoco_and_win32-openssh_with_server.ps1 both refresh the environment after installing OpenSSH so it can be used in the same console it was installed in.
- FIX: ssh-add is only run after ssh-agent is started.
- FIX: sshd and ssh-agent are always started (if installed), however, a warning to reboot is still generated if key based authentication is being used.
