### ISSUE TITLE
Is it necessary to run the various scripts in the install dir after installing with Chocolatey?

### ISSUE THREAD

**Issue by rkeithhill** [DarwinJS/ChocoPackages#70]
There are three scripts in the install folder and it's not clear to me if these need to be run post-install:
```
FixHostFilePermissions.ps1
FixUserFilePermissions.ps1
install-sshd.ps1
```
Do I need to run these manually or does the Chocolatey install execute these scripts (possibly dependent on one or more parameters)?

**Comment by DarwinJS** [comment]
The choco package is designed to do all install steps. Please report bugs if you find otherwise.
