### ISSUE TITLE
PowerShell PackageSources are invalid

### ISSUE THREAD

**Issue by corbob** [DarwinJS/ChocoPackages#78]
The PowerShell packages appear to link to the path in the repo without the branch designation, so they result in a 404. For instance pwsh points to https://github.com/DarwinJS/ChocoPackages/pwshpackages/pwsh/ when it should point to https://github.com/DarwinJS/ChocoPackages/blob/master/pwshpackages/pwsh/

**Comment by DarwinJS** [comment]
Fixed in 6.2.0
