### ISSUE TITLE
Create beta package of win32-openssh for beta testing

### ISSUE THREAD

**Issue by WSLUser** [DarwinJS/ChocoPackages#80]
Due to the many bugs, especially in the terminal world with win32-openssh on Windows 7, I would prefer to grab the latest from https://github.com/PowerShell/openssh-portable and the choco package run daily or weekly scan to detect changes and update accordingly. This would be maintained separately from the "stable" release.  The install should have some argument such as -pre to indicate to install the beta version.  The only other alternative is to manually pull from source and install every so often. This isn't very friendly to end users so having the process automated in a way that keeps the package current with "latestw_all" branch would be great.

**Comment by DarwinJS** [comment]
I currently do something similar for powershell-core previews (separate package identifier) and prereleases (uses chocolatey support for prereleases).  However, as far as I know the openssh project only builds binaries for master branch?  Binaries are required for the chocolatey packages.

**Comment by WSLUser** [comment]
I did find https://github.com/NoMoreFood/openssh-portable/releases/tag/v7.9-merge-2 But each of these binaries only includes one pull request. If they were able to bundled up that would be great. I'm not sure that's something you could do on your end or if the person who created the binaries has to combine them.

**Comment by WSLUser** [comment]
I filed an issue with the person since that would be the optimal solution.

**Comment by DarwinJS** [comment]
@WSLUser  - I think you should pursue it only through the official project - otherwise people are going to start reporting issues with interim builds the project does not release and therefore will disavow - which would be very confusing for casual users.

**Comment by WSLUser** [comment]
I don't think casual users will even use this project. More likely to use Putty because it "just works". As I said, still too many bugs for the average sysadmin. When you can't even use Vim, it quickly loses it's appeal. I'll run it to execute scripts and commands but any editing comes from Code.

**Comment by WSLUser** [comment]
Either I misread or something but https://github.com/NoMoreFood/openssh-portable/releases/tag/v7.9-merge-2 has all the binaries bundled for the issues/requests listed. These have all gone through the approval and testing process and just waiting to be merged. I removed my previous comments as a result of this. Do you think you could create an "alpha" package based of the binaries? Only calling it alpha because I did request officially and response was "this is already beta so no".

**Comment by DarwinJS** [comment]
@WSLUser - I don't really have the bandwidth to be picking up packaging for unofficial releases of this product - in fact OpenSSH is the most complex installer I've done to date - so there is a lot of testing involved in a good release.  You could re-use my chocolatey source and compile it and use a free open source feed at https://www.myget.org/opensource.

Or you could start a new package ID at Chocolatey - but there are more expectations around the package when you provide it publicly.

**Comment by WSLUser** [comment]
gotcha, I manually installed it for now with the expectation that Chocolately will overwrite it when the next official release comes out.

**Comment by DarwinJS** [comment]
Moved to:
