### ISSUE TITLE
(nexus-repository) Add more package parameters and document

### ISSUE THREAD

**Issue by mkevenaar** [DarwinJS/ChocoPackages#81]
Hi,

I think these would be nice to be configurable: 
```
$TargetFolder = "$env:programdata\nexus"
$TargetDataFolder = "$env:programdata\sonatype-work"
$servicename = 'nexus'
```
This one is already available. 
```
$NexusPort = '8081'
```

It would also be nice to describe the PP that are available inside the `<description>` element. 

e.g. like [bitvise-ssh-server](https://chocolatey.org/packages/bitvise-ssh-server)

Thanks,

Maurice

**Comment by mkevenaar** [comment]
Also it would be nice to be able to configure more than only the port :-) 

I think these would be nice to be configurable: 
```
$TargetFolder = "$env:programdata\nexus"
$TargetDataFolder = "$env:programdata\sonatype-work"
$servicename = 'nexus'
```
This one is already available. 
```
$NexusPort = '8081'
```

**Comment by DarwinJS** [comment]
moved to: https://gitlab.com/DarwinJS/ChocoPackages/issues/81
