### ISSUE TITLE
Add code block delimitters to package argument instructions

### ISSUE THREAD

**Issue by atruskie** [DarwinJS/ChocoPackages#84]
It looks like the chocolatey website applies some kind of style/markdown pass to the `description` field of a nuspec.

Unfortunately, this means that the install arguments section of the descriptions are often malformed:

![image](https://user-images.githubusercontent.com/1452968/58848895-863ae300-86cb-11e9-967c-99148c644511.png)

And the corresponding description:

https://github.com/DarwinJS/ChocoPackages/blob/bccb714249a80b2a298f925eee77791c60018fc2/pwshpackages/powershell-preview/powershell-preview.nuspec#L31-L46

I'm not sure if this is markdown; if it is, then perhaps wrapping that section in code block (`` ``` ``) delimiters would help ensure the formatting is not messed with.

**Comment by DarwinJS** [comment]
Moved to: https://gitlab.com/DarwinJS/ChocoPackages/issues/81
