### ISSUE TITLE
(nexus-repository) move to open JRE/JDK to avoid licensing issues

### ISSUE THREAD

**Issue by ferventcoder** [DarwinJS/ChocoPackages#87]
Hi @DarwinJS - has anyone requested this yet?

**Comment by DarwinJS** [comment]
Not that I'm aware of.  However, does the vendor test and support that version?  If not, maybe it should be a command line option to enable the open version?

I haven't been keeping up with the JRE licensing issues, so my questions may exhibit some ignorance of the details of the open version compatibility.

At my day job we tried to use AWS Corretto to underlie the CSI evaluation tool (CIS-CAT Pro) and immediately ran into compatibility problems with some of the benchmarks.  So it was obvious that not only the framework needed compability testing, but each benchmark as well.

**Comment by ferventcoder** [comment]
My understanding is that Nexus does support Open JRE.

I would get familiar with Oracle JRE changes ASAP, otherwise you may get a bill from your friends at Oracle.

**Comment by ferventcoder** [comment]
@DarwinJS https://help.sonatype.com/repomanager3/installation/java-runtime-environment is what I was reading about Sonatype supporting Open JRE/JDK

**Comment by DarwinJS** [comment]
Ok I will take this issue as a feature request and see about getting it in the next release - thanks for the tip off!

**Comment by DarwinJS** [comment]
@ferventcoder  - can you please advise the best chocolatey package to take a dependency on?
I see OpenJDK out there - but only want to put on the runtime if possible (minimize attack surface) and then I see these "Adopt*" java packages.  I don't see a plain "OpenJRE" or "OpenJavaRuntime" - any advice on the most compatible package would be appreciated!

**Comment by DarwinJS** [comment]
3.18.1.01 uses openjre via dependency on adoptopenjdkjre
