### ISSUE TITLE
OpenSSH - It appears that the default install command installs the sshd service with an unquoted service path.

### ISSUE THREAD

**Issue by les-tallman** [DarwinJS/ChocoPackages#88]
It appears that the default install command installs the sshd service with an unquoted service path. It is possible to escalate privileges by abusing misconfigured services. Specifically, this is possible if path to the service binary is not wrapped in quotes and there are spaces in the path.

Is there another option to install sshd, so the service path is quoted?

**Comment by DarwinJS** [comment]
Moved to: https://gitlab.com/DarwinJS/ChocoPackages/issues/88
