### ISSUE TITLE
pwsh-preview install-arguments \_

### ISSUE THREAD

**Issue by jborean93** [DarwinJS/ChocoPackages#92]
I'm curious as to why the `--install-arguments` have every `_` prefixed with `\_` like so https://github.com/DarwinJS/ChocoPackages/blob/d6967a91b3787020f4938aa0f8a8face8d47e134/pwshpackages/powershell-preview/powershell-preview.nuspec#L33. Is that actually the way the args should be specified?

It seems like some were changed with https://github.com/DarwinJS/ChocoPackages/commit/90666d7931b2551d194dc82825ba3dc09db2a26b but I would have assumed the old way was correct?

**Comment by DarwinJS** [comment]
I believe the escaping has (or had) to do with chocolatey command line parsing - as of the current chocolately release when this change was made.

Are you saying you can successfully trigger the switches without the escaping?  Please let me know and if so, what version of Chocolatey you are on.

FYI - If it works with or without escaping now, I'm inclined to leave it in to avoid bug reports by those on chocolatey versions that do care about it.

**Comment by DarwinJS** [comment]
Researched this a bit more.  The underbars are so that it will render correctly in Chocolatey meta data here: https://chocolatey.org/packages/powershell-preview
